# Generated by Django 4.2.7 on 2024-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmen', '0002_alter_starmen_options_starmen_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starmen',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
