# Generated by Django 4.2.7 on 2024-01-11 15:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('starmen', '0003_alter_starmen_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='starmen',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='starmen',
            name='starmen_sta_time_cr_bd8efc_idx',
        ),
        migrations.AlterField(
            model_name='starmen',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Еще редактируется'), (1, 'Опубликовано')], default=1),
        ),
        migrations.AddIndex(
            model_name='starmen',
            index=models.Index(fields=['time_create'], name='starmen_sta_time_cr_2bc967_idx'),
        ),
    ]
