# Generated by Django 4.2.7 on 2024-01-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starmen', '0005_category_starmen_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starmen',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='starmen.category'),
        ),
    ]
