# Generated by Django 4.2.7 on 2024-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmen', '0008_spouse_starmen_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='spouse',
            name='s_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
