# Generated by Django 4.2.7 on 2024-02-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starmen', '0009_spouse_s_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spouse',
            new_name='Company',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='starmen',
            options={'ordering': ['-time_create'], 'verbose_name': 'Известные люди', 'verbose_name_plural': 'Известные люди'},
        ),
        migrations.AlterModelManagers(
            name='starmen',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='starmen',
            name='spouse',
        ),
        migrations.AddField(
            model_name='starmen',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='starmen.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='starmen',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='starmen.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='starmen',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='starmen',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Еще редактируется'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='starmen',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='starmen.tagpost', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='starmen',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='starmen',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='starmen',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
