# Generated by Django 4.2.7 on 2024-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmen', '0010_rename_spouse_company_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.AlterField(
            model_name='starmen',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
